# Build and publish Docker images for multiple architectures.
#
# Pushing an image to codeberg's container registry
# The package owner will be the repo owner.
#
# This config also shows usage of yaml aliases and
# was taken from https://codeberg.org/6543/docker-images/src/commit/37e29c227717c1c07d2776cddcf14725bf952875/.woodpecker/hello.yml

when:
  branch: openMaxIO-main
  event: [push, pull_request, manual]

variables:
  - &file Dockerfile
  - &repo https://github.com/jamesagarside/openmaxio-object-browser

steps:
  dryrun:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      dockerfile: *file
      platforms: linux/arm/v7,linux/arm64/v8,linux/amd64
      dry_run: true
      repo: *repo
      tags: latest
    # when:
    #   event: pull_request
    #   path: *file

  publish:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      dockerfile: *file
      platforms: linux/arm/v7,linux/arm64/v8,linux/amd64
      repo: openmaxio-object-browser
      registry: registry.aquila.jgarside.co.uk
      tags: latest
      username: admin
      password:
        from_secret: aquila_registry_password
    # when:
    #   event: push
    #   path: *file
